# Metro Core plugin for SurviveMetro
# This is the home of all things Metro
# Author: MintyMonster

# Metro Claim keys:

metroclaimkeys:
  commands:
    # False = gets random command from list of commands and only uses one on Overclaim
    # True = gives all commands from list to player on Overclaim
    # use %player% (lowercase p) to use player's name
    # Feel free to add more commands to the list but ensure it fits the format
    multiple_commands: 'false'
    commands:
      - 'give %player% diamond 1'
      - 'give %player% emerald 1'

metrofly:
  messages: # Use colour codes here
    disableflight: '&6[Metro] &cLeaving claim - disabling flight'
    outofclaim: '&6[Metro] &cYou need to be in your own land, truced land or allied land to use this command.'
    enable: '&aEnabling flight'
    disable: '&cDisabling flight'

  commands:
    # These are all lists, so add as many as you want. Just ensure that you keep the format
    fly_ally_enable:
      - null
    fly_ally_disable:
      - null
    fly_truce_enable:
      - null
    fly_truce_disable:
      - null
    fly_own_enable:
      - null
    fly_own_disable:
      - null
    out_of_claim:
      - null

# /mod on||off
metromoderation:
  already_active:
    - '&7You already have an active session!'
    - '&7To close your session, use &e/mod off&7.'
  already_inactive:
    - '&7You don''t have an open session.'
    - '&7To open a session, use &e/mod on&7.'
  turn_on:
    commands:
      - 'minecraft:gamemode spectator %player%'
      - 'vanish %player% on'
      - 'lp user %player% parent add modding'
    messages:
      - '&d&o%player% &aopened a new &d&oModeration Session.'
      - '&7All of their actions will now be logged & monitored.'
  turn_off:
    commands:
      - 'minecraft:gamemode survival %player%'
      - 'vanish %player% off'
      - 'lp user %player% parent remove modding'
    messages:
      - '&d&o%player% &eclosed their &d&oModeration Session&7.'
      - '&7Actions are no longer being logged or monitored.'

# /admin on||off
metroadmin:
  already_active:
    - '&7You already have an active session!'
    - '&7To close your session, use &c/admin off&7.'
  already_inactive:
    - '&7You don''t have an open session.'
    - '&7To open a session, use &c/admin on&7.'
  turn_on:
    commands:
      - 'op %player%'
    messages:
      - '&c&o%player% &aopened an &c&oAdministration Session&7.'
      - '&7All of their actions will now be logged & monitored.'
  turn_off:
    commands:
      - 'deop %player%'
    messages:
      - '&c&o%player% &eclosed an &c&oAdministration Session&7.'
      - '&7Actions are no longer being logged or monitored.'

# /rtp
metrortp:
  # Imagine minimum is a negative number E.G 10,000 == -10,000
  minimum: 10000
  maximum: 10000
  # %x% = X coord
  # %y% = Y coord
  # %z% = Z coord
  # %player% = player
  commands:
    - 'cmi bossbarmsg %player% &7You have been teleported to &e%x%&7, &e%y%&7, &e%z% -t:2 -a:1 -p:1'
  messages:
    looking_for_safe: '&cLooking for a safe block...'
    found_safe: '&aSafe block found! &eTeleporting...'

# /bugreport <text>
bugreport:

  # Usage error message
  error: '&cUsage: &e[/bugreport submit <report>]'

  # Database addition error message
  database_error: '&cSomething went wrong, please contact staff'

  # Player report submission message
  report_submitted: '&aBug report submitted, thanks!'

  # Message sent to staff when bugreport submitted
  report_submitted_staff: '&e%player% &7just submitted a bug report! &e[/bugreport list]'

  # /bugreport list -> formatting
  list_formatting: '&7%id%: &c%name% &8>> &e%report%'

  # /bugreport fixed [id]
  bugreport_fixed: '&aBug [%id%] marked as fixed'

playerreport:

  # Usage error message
  error: '&cUsage: &e[/report submit <player> <report>]'

  # Database addition error message
  database_error: '&cSomething went wrong, please contact staff'

  # Player report submission message
  report_submitted: '&aPlayer report submitted, thanks!'

  # Message sent to staff when playerReport submitted
  # %player% = Player that submitted the report
  # %reported% = Player the report's about
  # %reason% = Report reason
  # %amount% = Amount of reports that player has submitted(total)
  report_submitted_staff:
    - '&6------ New player report -------'
    - '&eFrom&8: &7%player%'
    - '&eAbout&8: &7%reported%'
    - '&eReason: &7%reason%'
    - '&e%player%''s reports: &c%amount%'
    - '&6-------------------------------'

  # /report list -> formatting
  list_formatting: '&7%id%: &c%name% &8>> &e%report%'

  # If player tries to report self
  cant_report_self: '&cYou can''t report yourself.'

  # /report history <player> formatting
  report_submitted_history_format: '&7- &8[&a%date%&8] &c%player% &8>> &7%reason%'
  report_received_history_format: '&7- &8[&a%date%&8] &c%reporter% &8>> &c%reason%'

watchlist:
  added: '&aNew user added to watchlist &e[%player%]'

suggestion:
  added: '&aThank you for the suggestion!'

discord:

  # Server id
  guild_id: 571432265431777280

  # Channel ids

  playerreport_channel_id: 829465416534327398
  suggestions_channel_id: 829466256406085653
  watchlist_channel_id: 828621711187902534
  bugreport_channel_id: 829467871859310652
  notes_channel_id: 829465450274226206





