name: MetroCore
version: 1.0
main: uk.co.minty_studios.metrocore.MetroCore
author: MintyMonster
description: Core plugin for SurviveMetro
commands:
  metrocore:
    aliases: [mcore, mc, metro]
    description: Admin MetroCore commands
    usage: /metrocore
    permission-message: Permission denied.
    permission: metrocore.core
  admin:
    description: Admin mode toggle
    usage: /admin [on|off]
    permission-message: Permission denied.
    permission: metrocore.admin
  mod:
    description: Mod mode toggle
    usage: /mod [on|off]
    permission-message: Permission denied.
    permission: metrocore.mod
  bugreport:
    description: Report a bug!
    aliases: [brep, bug, br]
    usage: /bugreport submit <text>
    permission-message: Permission denied.
    permission: metrocore.core
  playerreport:
    description: Report a player!
    aliases: [report, rep, prep, preport]
    usage: /report submit <player> <reason>
    permission-message: Permission denied.
    permission: metrocore.core
  rtp:
    description: Randomly teleport throughout the world!
    aliases: [wild, randomteleport]
    usage: /rtp
    permission-message: Permission denied.
    permission: metrocore.core
  notes:
    description: Metro's very own sticky notes!
    aliases: [n, note]
    usage: /notes
    permission-message: Permission denied.
    permission: metrocore.admin
  suggestions:
    description: Suggestions!
    aliases: [suggest, suggestion, sugg, sug]
    usage: /suggest <text>
    permission-message: Permission denied.
    permission: metrocore.core
  watchlist:
    description: Add to the watchlist!
    aliases: [wlist, wl, watch]
    usage: /watchlist add <player> <reason>
    permission-message: Permission denied.
    permission: metrocore.mod
  discord:
    aliases: [disc, dcord, dc, d]
    description: All related Discord commands!
    usage: /discord
    permission-message: Permission denied.
    permission: metrocore.core
  # Add /dev || regular player > op ! op